[tool.poetry]
name = "ext-idp-group-mapper"
version = "2.0.0"
authors = [ "Amazon Web Services" ]
description = "Lambda implementation to change Cognito user groups to External Identity Provider groups in the JWT token"
packages = [
    { include = "*.py" },
    { include = "./**/*.py" },
    { include = "./**/**/*.py" },
    { include = "./config/*" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Apache-2.0",
]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.test.dependencies]
mock = "5.1.0"
moto = "5.0.7"
pytest = "8.2.1"
pytest-cov = "5.0.0"
pytest-env = "1.1.3"
PyYAML = "6.0.1"
setuptools = "70.0.0"
boto3-layer =  { path = "../layers/aws_boto3/", develop = true }
custom_boto3_init = { path = "../layers/custom_boto3_init", develop = true }

[tool.black]
line-length = 120

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120
profile = "black"

[build-system]
requires = [ "poetry-core>=1.0.8" ]
build-backend = "poetry.core.masonry.api"