# .prettierrc or .prettierrc.yaml
proseWrap: 'preserve'
trailingComma: 'none'
tabWidth: 4
semi: true
singleQuote: true
quoteProps: 'preserve'
printWidth: 120
overrides:
  - files:
      - '*.json'
      - '*.yml'
    options:
      tabWidth: 2
